apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medical-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sk-mini-project3/infra-medicare.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: medical-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
