apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
  labels:
    app: ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
        - name: ai
          image: <AI_IMAGE_PLACEHOLDER>
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOG_LEVEL
            - name: BACKEND_API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BACKEND_API_URL
          ports:
            - containerPort: 8001
