apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: <BACKEND_IMAGE_PLACEHOLDER>
          env:
            - name: DATABASE_URL
              value: "<REPLACE_WITH_DB_URL>"
          ports:
            - containerPort: 3000
