apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
  labels:
    app: medical-service

data:
  LOG_LEVEL: "INFO"
  AI_BASE_URL: "http://ai:8000"
  BACKEND_API_URL: "http://backend:8080"
  FRONTEND_API_BASE: "http://backend:8080"
  NODE_ENV: "production"
