apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
  labels:
    app: medical-service

data:
  LOG_LEVEL: "INFO"
  AI_BASE_URL: "http://ai-service:80"
  BACKEND_API_URL: "http://backend-service:80"
  FRONTEND_API_BASE: "http://backend-service:80"
  NODE_ENV: "production"
