apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: medical-service-frontend
          env:
            - name: REACT_APP_API_BASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BACKEND_API_URL
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_ENV
          ports:
            - containerPort: 80
