apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medical-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /ai
            pathType: Prefix
            backend:
              service:
                name: medical-ai-svc
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: medical-backend-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: medical-frontend-svc
                port:
                  number: 80
