resources:
  - frontend-deployment.yaml
  - backend-deployment.yaml
  - ai-deployment.yaml
  - service.yaml
  - ai-service.yaml
  - ingress.yaml

images:
  - name: <FRONTEND_IMAGE_PLACEHOLDER>
    newTag: "latest"
  - name: <BACKEND_IMAGE_PLACEHOLDER>
    newTag: "latest"
  - name: <AI_IMAGE_PLACEHOLDER>
    newTag: "latest"
